project:
  name: "eeg-vhp-pipeline"

paths:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  results_dir: "results"

eeg:
  montage: "pd_vhp_montage"
  sampling_rate: 512
  events:
    run_start: 333
    stim_on: 1
    stim_off: 11

preprocessing:
  bandpass:
    l_freq: 1.0
    h_freq: 80.0
    order: 4         # filter order (weâ€™ll use a 4th order Butterworth)
  notch:
    freqs: [50, 100, 150]
    Q: 30            # quality factor for notch (higher = narrower)
  rereference: "nose"    # for later; we won't change reference yet

analysis:
  psd:
    fmin: 1.0
    fmax: 60.0
    nperseg: 4096
  spectrogram:
    fmin: 1.0
    fmax: 60.0
    nperseg: 4096
    noverlap_ratio: 0.75


# ðŸ‘‡ THIS MUST BE AT THE ROOT (no extra indentation)
recordings:
  - "251120-1954_FREEEEG32_BOARD_baseline_with_VHP_powered_OFF"
  - "251120-1954_FREEEEG32_BOARD_baseline_with_VHP_powered_ON_stim_ON_no_contact_c1_f22_v100"
  - "251120-1954_FREEEEG32_BOARD_c1_f22_v100"
  - "251120-1954_FREEEEG32_BOARD_c1_f24_v100"
  - "251120-1954_FREEEEG32_BOARD_c1_f26_v100"
  - "251120-1954_FREEEEG32_BOARD_c1_f28_v100"
  - "251120-1954_FREEEEG32_BOARD_c1_f30_v100"
  - "251120-1954_FREEEEG32_BOARD_c1_f32_v100"
  - "251120-1954_FREEEEG32_BOARD_c1_f34_v100"
  - "251120-1954_FREEEEG32_BOARD_c1_f36_v100"
